### ISSUE TITLE
Adicionar BiomeJS ao projeto

### ISSUE THREAD

**Issue by gabrielluizep** [pji20242/frontend#9]
Para mantermos a qualidade do código é necessário que sigamos uma formatação padrão, conhecendo as tecnologias existentes para desempenhar tal função vemos em ascensão de popularidade a biblioteca BiomeJS dada sua  performance e facilidade de uso para o desenvolvedor:

DoD (Definition of Done):

- [x] Removido dependências referentes a biblioteca ESLint;
- [x] Instalada biblioteca BiomeJS;
- [x] Realizada configuração do BiomeJS;
- [x] `.vscode/` configurado de modo que torne o BiomeJS seja o formatador padrão e indique a extensão a utilizar; 
- [x] Definido pastas que serão ignoradas pelo processo de linting e formatting;
- [x] Adicionado comandos `npm run lint` e `npm run format`;
- [x] Realizado o processo de  linting no repositório;
- [x] Realizado o processo de formatting no repositório;
- [x] Não há indicações de erros em nenhum arquivo do repositório.
- [x]  Adicionar CI ao projeto para executar `npm run lint` e `npm run format` e indicar se não há erros.

**Comment by gugasth** [comment]
Implementações realizadas, issue fechada.
